# configs/config.yaml
defaults:
  - _self_
  - model: catboost  # Par d√©faut, on utilise xgboost. Change ici pour 'catboost' ou via la ligne de commande

data:
  train_path: "data/raw/train.csv"
  test_path: "data/raw/test.csv"
  submission_path: "data/raw/sample_submission.csv"
  output_path: "outputs/submission_${model.name}.csv" # Le nom du fichier s'adapte auto

training:
  n_splits: 5
  target_col: "loan_paid_back"
  id_col: "id"